export const HANDLE_ITEM = 'HANDLE_ITEM'
export const ADD_ITEM = 'ADD_ITEM'
export const REM_ITEM = 'REM_ITEM'
export const TOG_ITEM = 'TOG_ITEM'
export const SAVE_ITEM = 'SAVE_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
